/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package remoteobserverclient;

import java.awt.Container;
import java.awt.Toolkit;
import java.io.File;
import remoteserver.alpha.DBOperations;
import remoteserver.alpha.UsermasterBean;

/**
 *
 * @author Sood
 */
public class MainFrame extends javax.swing.JFrame {

    static UsermasterBean objBean;
    static Container container;
    public static int userId;
    static int activityId;
    static String username;

    /**
     * Creates new form MainFrameClient
     */
    public MainFrame() {
        initComponents();
    }

    public MainFrame(UsermasterBean objBean) {
        initComponents();
        username = objBean.getUserName();
        this.objBean = objBean;
        this.userId = objBean.getUser_id();
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        setResizable(true);
        container = getContentPane();
        setVisible(true);
    }

    public void logoutTime() {
        DBOperations objDB = new DBOperations();
        objDB.logoutTime();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        miLogout = new javax.swing.JMenuItem();
        mnuProfile = new javax.swing.JMenu();
        miProfileAccountDetail = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setBorderPainted(false);

        mnuFile.setText("File");

        miLogout.setText("Logout");
        miLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogoutActionPerformed(evt);
            }
        });
        mnuFile.add(miLogout);

        jMenuBar1.add(mnuFile);

        mnuProfile.setText("Profile");

        miProfileAccountDetail.setText("Profile Account Detail");
        miProfileAccountDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProfileAccountDetailActionPerformed(evt);
            }
        });
        mnuProfile.add(miProfileAccountDetail);

        jMenuBar1.add(mnuProfile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miProfileAccountDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProfileAccountDetailActionPerformed
        container.removeAll();
        container.setVisible(false);
        ProfileDetail obj = new ProfileDetail();
        obj.setBounds(350, 10, 500, 580);
        container.add(obj);
        container.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_miProfileAccountDetailActionPerformed

    private void miLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogoutActionPerformed
        ScreenShot.flag = false;
        

        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                ZippingData zp = new ZippingData();
                zp.start();
                try {
                    if (zp.isAlive()) {
                        zp.join();
                    }
                } catch (Exception e1) {
                    System.out.println("Exception in Alive in Main Frame" + e1);
                }
                UploadThread up = new UploadThread("/Users/sahilsood/NetBeansProjects/Zip files"+File.separator+MainFrame.username+LoginFrame.maxactivityId+".zip");
                up.start();
                if (up.isAlive()) {
                    try {
                        up.join();
                        System.out.println("uploaded");
                    } catch (Exception e) {
                    }
                }
            }
        });
        t.start();
        logoutTime();
        setVisible(false);
        new LoginFrame().setVisible(true);




    }//GEN-LAST:event_miLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JMenuItem miProfileAccountDetail;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuProfile;
    // End of variables declaration//GEN-END:variables

    private Object Date() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
