/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package remoteobserverserver;

import java.awt.Container;
import java.awt.Toolkit;
import remoteobserver.alpha.UsermasterBean;

/**
 *
 * @author Sood
 */
public class MainFrame extends javax.swing.JFrame {
    public static UsermasterBean objBean;
    public static Container container;
    public static int userId;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }
    public MainFrame(UsermasterBean objBean)
    {
        initComponents();
        this.objBean = objBean;
        this.userId = objBean.getUserId();
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        setResizable(false);
        container = getContentPane();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mbMainFrame = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        miLogout = new javax.swing.JMenuItem();
        mnuProfile = new javax.swing.JMenu();
        miProfileAccountDetail = new javax.swing.JMenuItem();
        mnuUserMaintenance = new javax.swing.JMenu();
        miUserAccountDetail = new javax.swing.JMenuItem();
        mnuServer = new javax.swing.JMenu();
        miStartServer = new javax.swing.JMenuItem();
        mnuReports = new javax.swing.JMenu();
        miUserAccountReport = new javax.swing.JMenuItem();
        miUserActivityReport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mbMainFrame.setName(""); // NOI18N

        mnuFile.setText("File");

        miLogout.setText("Logout");
        miLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogoutActionPerformed(evt);
            }
        });
        mnuFile.add(miLogout);

        mbMainFrame.add(mnuFile);

        mnuProfile.setText("Profile");

        miProfileAccountDetail.setText("Profile Account Detail");
        miProfileAccountDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProfileAccountDetailActionPerformed(evt);
            }
        });
        mnuProfile.add(miProfileAccountDetail);

        mbMainFrame.add(mnuProfile);

        mnuUserMaintenance.setText("User Maintenance");

        miUserAccountDetail.setText("User Account Detail");
        miUserAccountDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUserAccountDetailActionPerformed(evt);
            }
        });
        mnuUserMaintenance.add(miUserAccountDetail);

        mbMainFrame.add(mnuUserMaintenance);

        mnuServer.setText("Server");
        mnuServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuServerActionPerformed(evt);
            }
        });

        miStartServer.setText("Start Server");
        miStartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miStartServerActionPerformed(evt);
            }
        });
        mnuServer.add(miStartServer);

        mbMainFrame.add(mnuServer);

        mnuReports.setText("Reports");

        miUserAccountReport.setText("User Account Report");
        miUserAccountReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUserAccountReportActionPerformed(evt);
            }
        });
        mnuReports.add(miUserAccountReport);

        miUserActivityReport.setText("User Activity Report");
        miUserActivityReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUserActivityReportActionPerformed(evt);
            }
        });
        mnuReports.add(miUserActivityReport);

        mbMainFrame.add(mnuReports);

        setJMenuBar(mbMainFrame);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miProfileAccountDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProfileAccountDetailActionPerformed
    container.removeAll();
    container.setVisible(false);
    
    ProfileDetail obj = new ProfileDetail();
    obj.setBounds(450,60,500,580);
    
    container.add(obj);
    container.setVisible(true);
     // TODO add your handling code here:
    }//GEN-LAST:event_miProfileAccountDetailActionPerformed

    private void mnuServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuServerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuServerActionPerformed

    private void miUserAccountDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUserAccountDetailActionPerformed
    container.removeAll();
    container.setVisible(false);
    
    UserDetail obj = new UserDetail();
    obj.setBounds(400,30,530,650);
    
    container.add(obj);
    container.setVisible(true);
   // TODO add your handling code here:
    }//GEN-LAST:event_miUserAccountDetailActionPerformed

    private void miUserAccountReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUserAccountReportActionPerformed
    setSize(Toolkit.getDefaultToolkit().getScreenSize());
    new UserReport().setVisible(true);
     
          // TODO add your handling code here:
    }//GEN-LAST:event_miUserAccountReportActionPerformed

    private void miUserActivityReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUserActivityReportActionPerformed
     
     new UserActivityReport().setVisible(true);
     // TODO add your handling code here:
    }//GEN-LAST:event_miUserActivityReportActionPerformed

    private void miLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogoutActionPerformed
    
    setVisible(false);
    new LoginFrame().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_miLogoutActionPerformed

    private void miStartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miStartServerActionPerformed
    
    SocketServer ss = new SocketServer();
    ss.start();// TODO add your handling code here:
    }//GEN-LAST:event_miStartServerActionPerformed

    /**
 
     * @param args the command line argument
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar mbMainFrame;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JMenuItem miProfileAccountDetail;
    private javax.swing.JMenuItem miStartServer;
    private javax.swing.JMenuItem miUserAccountDetail;
    private javax.swing.JMenuItem miUserAccountReport;
    private javax.swing.JMenuItem miUserActivityReport;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuProfile;
    private javax.swing.JMenu mnuReports;
    private javax.swing.JMenu mnuServer;
    private javax.swing.JMenu mnuUserMaintenance;
    // End of variables declaration//GEN-END:variables
}